"""课程管理服务 —— 从 db.repositories.course 重导出"""
from app.db.repositories.course import (
    create_course,
    list_teacher_courses,
    get_teacher_course,
    update_course,
    archive_course,
    regenerate_code,
    list_course_students,
    add_students_by_username,
    remove_student,
    join_course,
    list_student_courses,
    get_student_course,
    quit_course,
    require_enrollment as _require_enrollment,
    require_teacher_course as _require_teacher_course,
    calc_total_score as _calc_total_score,
    _gen_unique_code as _gen_unique_code,
)
